# Default values for edgeinsight-datahandler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: edgeinsight.azurecr.io/edgeinsight-datahandler
  pullPolicy: IfNotPresent
  # Replaced by helm pipeline, do not change!
  #tag: PLACEHOLDER_TAG
imagePullSecrets:
  - name: edgeinsight

rabbitmq:
  host: dev-rabbitmq
  port: "5672"
  user: edgeadmin
  password: abb1234
  dataVhost: data
  dataExchange: data.edgeinsight.abb
  commandVhost: data
  commandExchange: commands.edgeinsight.abb
  monitoringVhost: monitoring
  monitoringExchange: devops.edgeinsight.abb

datahandler:
  name: edgeinsight-datahandler
  amqpMetrics: "false"
  amqpLog: "false"
  metricsInterval: "15000"
  logInterval: "10000"

storage:
  rootPath: /app/datastore
  useDisk: "true"