apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: edgeinsight
spec:
  # Project description
  description: EdgeInsight deployment project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: '*'
      server: '*'

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'